In [8]:
import pandas as pd
import numpy as np
import spacy
# import scispacy
import spacy
import re
from spacy.pipeline import EntityRuler
nlp = spacy.load("en_ner_bionlp13cg_md")
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC

In [9]:
## Loading the dfs
df = pd.read_csv("everything.csv", index_col=0)
df_doc = pd.read_csv('specialists.csv')

In [30]:
# Categorize.  Set dictionaries
col = ['label', 'anat_symp_lem', 'symp_lem']
df = df[col]
df = df[(pd.notnull(df['anat_symp_lem'])) & (pd.notnull(df['symp_lem']))]
df['category_id'] = df['label'].factorize()[0]
category_id_df = df[['label', 'category_id']].drop_duplicates().sort_values('category_id')
category_to_id = dict(category_id_df.values)
id_to_category = dict(category_id_df[['category_id', 'label']].values)

,label,anat_symp_lem,symp_lem,category_id
19,Ophthalmologist,mucus lymph node eye sore gland ...,eye redness - result inflammation widen tiny...,2
71,Ophthalmologist,uvea eye vitreous eyeball eye ...,print overview eye floater open pop-up dialog ...,2
72,Ophthalmologist,eye retinal detachment vitreous eye...,print overview retinal detachment open pop-up ...,2
73,Ophthalmologist,optic nerve tissue-like scar epiretina...,print overview part eye open pop-up dialog box...,2
74,Ophthalmologist,optic nerve eye cornea iris arte...,print overview open-angle glaucoma open pop-up...,2
...,...,...,...,...
930,Ophthalmologist,eye eyeglasse clear,wear eyeglass child eye do n t seem clear,2
931,Ophthalmologist,eye black float,black float front eye,2
932,Ophthalmologist,nettle,insect bite swell like nettle,2
933,Ophthalmologist,eye painful mirror,smoky eye also painful mirror,2
934,Ophthalmologist,rash grow painful,rash do n t really heal grow painful,2

In [39]:
# Train model
X_train, X_test, y_train, y_test = train_test_split(df['anat_symp_lem'], df['label'], random_state = 42)
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
clf = LogisticRegression().fit(X_train_tfidf, y_train)

ValueError: Found input variables with inconsistent numbers of samples: [733, 978]

In [175]:
# USER INPUT
text = ["my head hurts and eyes are watering. ache in temple area."]
# text = ['my eyes hurt around the upper area. i am experiencing fever and ache.']
location = 'Pampanga'

In [176]:
doc = ''.join(list(clf.predict(count_vect.transform(text))))
doc

ValueError: X has 2 features per sample; expecting 1450

In [36]:
# Results
df_res = df_doc[(df_doc['Specialty ']==doc) & (df_doc['Location'].str.contains(location))]
df_online = df_doc.replace(np.nan, '', regex=True)
df_online = df_online[(df_online['Specialty ']==doc) & (df_online['Online']!="")]

In [23]:
# Print results
if len(df_res) == 0:
    print(f"""      Searched for: {doc} in {location}
      None found in the list
      
      Another option is consulting via telemedicine with the following specialists:
      """)
    for index,row in df_online.iterrows():
        print(f"""
            Doctor's Name: {row["Doctor"]}
            Link for Telemedicine Consult: {row["Online"]}
        """)
else:
    print(f"       Searched for: {doc} in {location}")
    for index,row in df_res.iterrows():
        print(f"""
            Doctor's Name: {row["Doctor"]}
            Clinic Address: {(row["Clinic"])}
            Contact Details For Appointment: {row["Contact"]}
        """)

       Searched for: Ear, Nose, Throat in Pampanga

            Doctor's Name: Dr. Jeffrey Pangilinan
            Clinic Address: MacArthur Highway, Mabalacat, 2010 Pampanga
            Contact Details For Appointment: 0932 429 2684


            Doctor's Name: Dr. Joman Q. Laxamana
            Clinic Address: Km.78 MacArthur Highway, Brgy, San Fernando, 2000 Pampanga
            Contact Details For Appointment: 0932 856 4258

In [40]:
df = pd.read_csv("everything.csv", index_col=0)
df_doc = pd.read_csv('specialists.csv')

In [41]:
df

,label,symptoms,anatomic,anatomic_sent,symptoms_clean,symp_lem,symp_label,neg,site,anat_symp,anat_symp_lem,anat_lem
0,"Ear, Nose, Throat","['ear pain', 'itching and irritation in and ar...","{'sore glands', 'otitis externa', 'pus-like', ...","{This is known as chronic otitis externa.', 'S...",'ear pain 'itching irritation around ear canal...,ear pain itching irritation around ear can...,pain irritation redness swelling pressure full...,n't attempt squeeze pimples boils ear lead inf...,www.nhsinform.scot,"{'sore glands', 'otitis externa', 'pus-like', ...",sore gland otitis externa pus-like ...,sore gland otitis externa pus-like ...
1,"Ear, Nose, Throat","['frequent sneezing', 'runny or blocked nose',...","{'mucus', 'chest', 'eyes', ""nose'"", 'earache',...","{['frequent sneezing', 'runny or blocked nose'...",'frequent sneezing 'runny blocked nose 'itchy ...,frequent sneeze runny block nose itchy r...,sneezing blocked itchy red itchy throat cough ...,NaN,www.nhsinform.scot,"{'mucus', 'chest', 'eyes', ""nose'"", 'earache',...",mucus chest eye nose earache ...,mucus chest eye nose earache ...
2,"Ear, Nose, Throat","['a sore throat', 'a blocked or runny nose', '...","{'taste', 'eyes', 'muscles', 'muscle', 'ear', ...","{['a sore throat', 'a blocked or runny nose', ...",sore throat blocked runny nose 'sneezing cough...,sore throat block runny nose sneeze cough ho...,blocked runny nose sneezing cough hoarse voice...,NaN,www.nhsinform.scot,"{'taste', 'eyes', 'muscles', 'muscle', 'ear', ...",taste eye muscle muscle ear e...,taste eye muscle muscle ear e...
3,"Ear, Nose, Throat","['vertigo – the sensation that you, or the env...","{'ear', 'Ménière'}",{Some people may experience several attacks ea...,'vertigo - sensation environment around moving...,vertigo - sensation environment around move ...,vertigo spinning tinnitus hearing loss difficu...,NaN,www.nhsinform.scot,"{'ear', 'Ménière'}vertigo spinning tinnitus he...",ear ménière vertigo spin tinnitus hear lo...,ear ménière
4,"Ear, Nose, Throat","['a mild headache', 'nausea (feeling sick)', '...","{'eye', 'brain', 'leg', 'skull', 'body', 'brui...","{However, seek medical assistance if your chil...",mild headache 'nausea feeling sick 'mild dizzi...,mild headache nausea feel sick mild dizzin...,mild headache nausea vision unconsciousness di...,injury clear fluid nose could cerebrospinal fl...,www.nhsinform.scot,"{'eye', 'brain', 'leg', 'skull', 'body', 'brui...",eye brain leg skull body brui...,eye brain leg skull body brui...
...,...,...,...,...,...,...,...,...,...,...,...,...
975,"Ear, Nose, Throat",Suddenly my face could not move to the right. ...,"{'face', 'saliva', 'eyes'}",{Suddenly my face could not move to the right....,suddenly face could not move right saliva drip...,suddenly face could not move right saliva drip...,NaN,saliva dripping eyes,complaints,"{'face', 'saliva', 'eyes'}",face saliva eye,face saliva eye
976,Neurologist,"My grandfather had a stroke, he can no longer ...",set(),set(),grandfather stroke no longer walk feet,grandfather stroke no long walk foot,stroke,walk,complaints,()stroke,stroke,set
977,Neurologist,Our cousin's head turned. The motor collided a...,set(),set(),cousin 's head turned motor collided lost cons...,cousin s head turn motor collide lose consci...,NaN,NaN,complaints,(),,set
978,Neurologist,I feel like I will fall to the right when I walk,set(),set(),feel like fall right walk,feel like fall right walk,fall,NaN,complaints,()fall,fall,set
979,Neurologist,It was getting dark around me then I suddenly ...,set(),set(),getting dark around suddenly fainted,get dark around suddenly faint,dark,NaN,complaints,()dark,dark,set

In [42]:
# Categorize.  Set dictionaries
df = pd.read_csv("everything.csv", index_col=0)
df_doc = pd.read_csv('specialists.csv')
col = ['label', 'anat_symp_lem', 'symp_lem']
df = df[col]
df = df[(pd.notnull(df['anat_symp_lem'])) & (pd.notnull(df['symp_lem']))]
df['category_id'] = df['label'].factorize()[0]
category_id_df = df[['label', 'category_id']].drop_duplicates().sort_values('category_id')
category_to_id = dict(category_id_df.values)
id_to_category = dict(category_id_df[['category_id', 'label']].values)

,label,anat_symp_lem,symp_lem,category_id
0,"Ear, Nose, Throat",sore gland otitis externa pus-like ...,ear pain itching irritation around ear can...,0
439,"Ear, Nose, Throat",tonsillar pharyngeal fever,mononucleosis classically fever lymphadenopath...,0
438,"Ear, Nose, Throat",thyroid gland innervate organ sinus ...,otalgia ear pain divide two broad category pri...,0
437,"Ear, Nose, Throat",posterior pharynx retropharyngeal abscess...,retropharyngeal abscess uncommon potentially l...,0
436,"Ear, Nose, Throat",cricopharyngeus esophagus submucosal l...,zenker s diverticulum type diverticulum deve...,0
...,...,...,...,...
391,Ophthalmologist,eyelashe red eyelid swollen eyelid eye...,blepharitis medical term eyelid inflammation c...,2
392,Ophthalmologist,eye eye twitch muscle eye eyelid...,eye twitch involuntary spasm muscle eyelid ble...,2
606,Ophthalmologist,eye cornea globe permanently [ eye...,ectropion outward turn eyelid margin typically...,2
386,Ophthalmologist,eye cornea eye eyelid interstiti...,keratitis inflammation cornea eye keratitis si...,2
612,Ophthalmologist,vessel fundus visual nystagmus increase s...,clinical characteristic achromatopsia reduce v...,2

In [47]:
from sklearn.model_selection import train_test_split

In [95]:
X_train, X_test, y_train, y_test = train_test_split(df['anat_symp_lem'], df['label'], random_state = 42)
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X_train)
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
clf = LogisticRegression().fit(X_train_tfidf, y_train)

In [ ]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [96]:
# Let's fetch all the possible text data
df = pd.read_csv("everything.csv", index_col=0)
df_doc = pd.read_csv('specialists.csv')
col = ['label', 'anat_symp_lem', 'symp_lem']
df = df[col]
df = df[(pd.notnull(df['anat_symp_lem'])) & (pd.notnull(df['symp_lem']))]
df['category_id'] = df['label'].factorize()[0]
category_id_df = df[['label', 'category_id']].drop_duplicates().sort_values('category_id')
category_to_id = dict(category_id_df.values)
id_to_category = dict(category_id_df[['category_id', 'label']].values)

In [97]:
df["data"] = df["anat_symp_lem"]

In [98]:
vectorizer = CountVectorizer()
vectorizer.fit(df.data)
vectorizer.vocabulary_

{'sore': 1322,
 'gland': 596,
 'otitis': 1013,
 'externa': 478,
 'pus': 1167,
 'like': 800,
 'jaw': 745,
 'watery': 1637,
 'ear': 410,
 'throat': 1478,
 'hair': 633,
 'follicle': 541,
 'skin': 1301,
 'pain': 1022,
 'irritation': 742,
 'redness': 1183,
 'swelling': 1428,
 'pressure': 1140,
 'fullness': 571,
 'discharge': 370,
 'tenderness': 1458,
 'swollen': 1430,
 'hear': 643,
 'loss': 817,
 'itch': 743,
 'discomfort': 372,
 'stenosis': 1354,
 'mirror': 884,
 'mucus': 904,
 'chest': 226,
 'eye': 486,
 'nose': 967,
 'earache': 411,
 'grain': 607,
 'sneeze': 1315,
 'block': 125,
 'itchy': 744,
 'red': 1181,
 'cough': 314,
 'postnasal': 1125,
 'drip': 386,
 'anosmia': 41,
 'facial': 495,
 'headache': 642,
 'tiredness': 1495,
 'fatigue': 503,
 'shortness': 1281,
 'breath': 149,
 'wheezing': 1641,
 'fever': 513,
 'taste': 1444,
 'muscle': 908,
 'face': 494,
 'runny': 1218,
 'hoarse': 659,
 'voice': 1626,
 'high': 656,
 'temperature': 1452,
 'cold': 269,
 'ménière': 915,
 'vertigo': 1603,
 'spin': 1333,
 'tinnitus': 1493,
 'difficulty': 362,
 'lightheadedness': 799,
 'sensitivity': 1263,
 'fall': 497,
 'buzzing': 173,
 'grind': 620,
 'nausea': 924,
 'vomiting': 1628,
 'balance': 95,
 'problem': 1142,
 'unsteady': 1559,
 'dark': 342,
 'hearing': 644,
 'brain': 143,
 'leg': 784,
 'skull': 1302,
 'body': 137,
 'bruise': 154,
 'cerebrospinal': 209,
 'fluid': 537,
 'head': 641,
 'mild': 881,
 'vision': 1619,
 'unconsciousness': 1555,
 'sleepy': 1306,
 'injury': 699,
 'clear': 255,
 'leaking': 781,
 'bleeding': 119,
 'bruising': 155,
 'speak': 1326,
 'slur': 1309,
 'speech': 1328,
 'weakness': 1639,
 'seizure': 1255,
 'memory': 865,
 'irritability': 739,
 'hurt': 664,
 'change': 220,
 'consciousness': 293,
 'sink': 1292,
 'fontanelle': 543,
 'back': 93,
 'soil': 1319,
 'mouth': 897,
 'twitch': 1540,
 'breathing': 150,
 'tear': 1445,
 'febrile': 506,
 'lobe': 813,
 'neck': 927,
 'parietal': 1055,
 'frontal': 566,
 'cerebellum': 207,
 'drowsiness': 394,
 'floater': 533,
 'fit': 525,
 'smell': 1311,
 'forgetfulness': 552,
 'numbness': 974,
 'dysarthria': 403,
 'rib': 1206,
 'heart': 645,
 'bone': 138,
 'stridor': 1373,
 'inflammation': 694,
 'bark': 98,
 'croaky': 327,
 'sleepiness': 1304,
 'ulcer': 1545,
 'tooth': 1506,
 'lymph': 822,
 'node': 958,
 'lip': 808,
 'gum': 624,
 'betel': 111,
 'gums': 626,
 'white': 1643,
 'patch': 1061,
 'lump': 819,
 'swallow': 1421,
 'chill': 230,
 'joint': 750,
 'lung': 821,
 'extra': 479,
 'kidney': 755,
 'saliva': 1227,
 'swell': 1427,
 'irritated': 741,
 'painful': 1023,
 'bad': 94,
 'tingle': 1491,
 'burn': 168,
 'sensation': 1261,
 'scarring': 1239,
 'bleed': 118,
 'wound': 1649,
 'confusion': 287,
 'concussion': 284,
 'irritable': 740,
 'leak': 780,
 'black': 116,
 'stomach': 1362,
 'buccal': 157,
 'midazolam': 876,
 'upper': 1560,
 'hand': 638,
 'rectum': 1180,
 'stiffness': 1360,
 'object': 978,
 'jerk': 749,
 'electric': 425,
 'shock': 1278,
 'vaginal': 1573,
 'eyelid': 493,
 'salivary': 1228,
 'tongue': 1502,
 'blood': 128,
 'vessel': 1607,
 'oral': 995,
 'thrush': 1483,
 'dry': 396,
 'photophobia': 1089,
 'dryness': 397,
 'tonsil': 1503,
 'contact': 295,
 'not': 970,
 'ring': 1209,
 'bright': 151,
 'liver': 811,
 'puffiness': 1156,
 'armpit': 63,
 'glandular': 597,
 'adenoid': 12,
 'roof': 1213,
 'rash': 1175,
 'tender': 1457,
 'ulcerative': 1548,
 'gingivitis': 595,
 'increase': 686,
 'migraine': 879,
 'visual': 1620,
 'blind': 121,
 'spot': 1345,
 'dizzy': 380,
 'paralysis': 1047,
 'garble': 580,
 'throbbing': 1480,
 'aura': 81,
 'stroke': 1375,
 'eyelash': 491,
 'conjunctiva': 289,
 'allergy': 25,
 'small': 1310,
 'greyish': 618,
 'limb': 801,
 'lewy': 795,
 'parkinson': 1056,
 'depression': 351,
 'drop': 392,
 'one': 992,
 'side': 1288,
 'garbled': 581,
 'trigeminal': 1525,
 'neuralgia': 939,
 'forehead': 549,
 'cheek': 222,
 'sharp': 1275,
 'shoot': 1279,
 'psychological': 1150,
 'intracranial': 720,
 'personality': 1084,
 'severe': 1271,
 'urinary': 1563,
 'drool': 387,
 'insomnia': 704,
 'excessive': 473,
 'hallucination': 634,
 'parotid': 1057,
 'abdominal': 1,
 'cerebral': 208,
 'dura': 401,
 'monocytogene': 892,
 'eosinophilic': 444,
 'spinal': 1335,
 'tap': 1441,
 'outer': 1016,
 'membrane': 863,
 'surface': 1415,
 'cord': 302,
 'infant': 689,
 'toilet': 1501,
 'meninge': 866,
 'jugular': 751,
 'septic': 1267,
 'spleen': 1339,
 'pia': 1093,
 'bloodstream': 129,
 'airway': 23,
 'fruit': 570,
 'wake': 1632,
 'sluggishness': 1308,
 'bulge': 163,
 'gait': 575,
 'abscess': 4,
 'eardrum': 412,
 'canal': 180,
 'swab': 1420,
 'secretion': 1248,
 'muffled': 905,
 'pinna': 1101,
 'ceruman': 213,
 'auricle': 83,
 'blockage': 126,
 'peripheral': 1078,
 'vestibular': 1608,
 'saccule': 1222,
 'iron': 737,
 'nerve': 933,
 'bed': 106,
 'and': 33,
 'forth': 556,
 'utricle': 1568,
 'float': 532,
 'ringing': 1210,
 'jawbone': 746,
 'thyroid': 1486,
 'artery': 69,
 'cranial': 319,
 'vein': 1585,
 'tmj': 1498,
 'cochlea': 266,
 'carotid': 191,
 'cardiovascular': 190,
 'neuroma': 943,
 'frostbitten': 569,
 'foot': 545,
 'bluish': 132,
 'toe': 1500,
 'superficial': 1406,
 'frostbite': 568,
 'nail': 916,
 'blister': 124,
 'grayish': 615,
 'yellow': 1650,
 'warmer': 1635,
 'tingling': 1492,
 'wax': 1638,
 'earwax': 413,
 'mastoiditis': 844,
 'bloody': 130,
 'incus': 687,
 'mastoid': 843,
 'more': 895,
 'significant': 1290,
 'tube': 1532,
 'filled': 519,
 'nasal': 919,
 'congestion': 288,
 'clogged': 259,
 'smoke': 1313,
 'tearing': 1446,
 'cleft': 256,
 'palate': 1027,
 'suture': 1419,
 'midline': 878,
 'sagittal': 1225,
 'socket': 1317,
 'scaphocephaly': 1236,
 'anterior': 43,
 'fontanel': 542,
 'lambdoid': 766,
 'deformity': 348,
 'grow': 622,
 'lethargy': 792,
 'blindness': 122,
 'spine': 1336,
 'brainstem': 144,
 'nervous': 934,
 'syrinx': 1437,
 'choking': 232,
 'bump': 166,
 'blurry': 134,
 'dilated': 365,
 'pupil': 1163,
 'cl': 252,
 'shrub': 1285,
 'equine': 459,
 'egg': 423,
 'sight': 1289,
 'coma': 279,
 'clog': 258,
 'sinuse': 1295,
 'nostril': 969,
 'tj': 1497,
 'gastroesophageal': 584,
 'uneven': 1557,
 'reflux': 1186,
 'foreign': 550,
 'lesion': 790,
 'umbilical': 1550,
 'arch': 57,
 'clench': 257,
 'organ': 1001,
 'fece': 507,
 'abdoman': 0,
 'acellular': 6,
 'thigh': 1474,
 'pulmonary': 1157,
 'embolism': 426,
 'contraction': 299,
 'lockjaw': 815,
 'cut': 336,
 'larynx': 775,
 'scratchy': 1245,
 'phlegm': 1088,
 'esophagus': 469,
 'acid': 7,
 'spicy': 1332,
 'rough': 1217,
 'heartburn': 647,
 'coughing': 315,
 'epiglottis': 450,
 'pharynx': 1087,
 'nasopharynx': 923,
 'oropharynx': 1007,
 'esophageal': 466,
 'laryngopharynx': 774,
 'valve': 1576,
 'strep': 1367,
 'pubic': 1155,
 'area': 59,
 'anogenital': 40,
 'wart': 1636,
 'anus': 49,
 'plantar': 1106,
 'hpv': 663,
 'related': 1191,
 'genital': 587,
 'peni': 1067,
 'immune': 678,
 'system': 1438,
 'suppressing': 1410,
 'vagina': 1572,
 'oropharyngeal': 1006,
 'flat': 529,
 'anal': 32,
 'scrotum': 1246,
 'transplant': 1517,
 'mucous': 903,
 'growth': 623,
 'uterus': 1567,
 'vulva': 1631,
 'topped': 1509,
 'cervix': 217,
 'unsightly': 1558,
 'verrucous': 1599,
 'variety': 1577,
 'erythroplakia': 465,
 'smokeless': 1314,
 'tobacco': 1499,
 'noncancerous': 963,
 'leukoplakia': 793,
 'swallowing': 1422,
 'painless': 1025,
 'mineral': 883,
 'lichen': 796,
 'inner': 701,
 'flaky': 526,
 'areola': 61,
 'nipple': 955,
 'candida': 183,
 'esophagitis': 467,
 'soreness': 1323,
 'albican': 24,
 'gritty': 621,
 'duct': 398,
 'sublingual': 1393,
 'submandibular': 1395,
 'corneal': 304,
 'non': 962,
 'ocular': 986,
 'sicca': 1287,
 'sand': 1231,
 'cavitie': 198,
 'light': 798,
 'lingual': 806,
 'frenulum': 563,
 'newborn': 951,
 'tie': 1490,
 'ankyloglossia': 39,
 'right': 1208,
 'ventricular': 1593,
 'wall': 1633,
 'vsd': 1630,
 'chromosome': 240,
 'gastrointestinal': 585,
 'lymphatic': 824,
 'tetralogy': 1469,
 'truncus': 1529,
 'arteriosus': 67,
 'bulbous': 162,
 'fetal': 511,
 'ventricle': 1591,
 'parathyroid': 1052,
 'breastbone': 148,
 'thymus': 1485,
 'septal': 1265,
 'feed': 508,
 'split': 1342,
 'impairment': 680,
 'pad': 1021,
 'scarlet': 1238,
 'tonsillar': 1504,
 'cellulitis': 205,
 'peritonsillar': 1080,
 'tonsils': 1505,
 'dna': 381,
 'intestinal': 714,
 'bowel': 140,
 'shallow': 1272,
 'colitis': 270,
 'peptic': 1069,
 'papillae': 1040,
 'bud': 159,
 'palm': 1033,
 'buttock': 171,
 'sol': 1320,
 'digestive': 364,
 'tract': 1515,
 'bladder': 117,
 'tremor': 1520,
 'monotone': 893,
 'choke': 231,
 'sweet': 1426,
 'gastric': 583,
 'sugar': 1404,
 'free': 562,
 'interdental': 710,
 'cleaner': 254,
 'root': 1214,
 'feeding': 509,
 'brush': 156,
 'cranny': 322,
 'premolar': 1137,
 'molar': 889,
 'cavity': 199,
 'toothache': 1507,
 'sac': 1220,
 'ulceration': 1547,
 'coronary': 307,
 'gingiva': 593,
 'gingival': 594,
 'gumline': 625,
 'pill': 1097,
 'emphysema': 430,
 'alveolus': 29,
 'sputum': 1346,
 'sleep': 1303,
 'disruption': 376,
 'patches': 1062,
 'reddish': 1182,
 'tease': 1448,
 'survivor': 1417,
 'fetus': 512,
 'trunk': 1530,
 'placenta': 1104,
 'ataxia': 75,
 'abnormality': 3,
 'microcephaly': 874,
 'otolith': 1015,
 'semicircular': 1260,
 'labyrinth': 759,
 'trouble': 1528,
 'endolymph': 434,
 'scar': 1237,
 'plaque': 1107,
 'disease': 374,
 'salad': 1226,
 'causeslewy': 195,
 'olfactory': 990,
 'autonomic': 86,
 'spatial': 1325,
 'meth': 872,
 'eat': 414,
 'cramp': 318,
 'flashback': 528,
 'uvea': 1569,
 'vitreous': 1625,
 'eyeball': 487,
 'jelly': 747,
 'substance': 1401,
 'retinal': 1197,
 'speck': 1327,
 'stringy': 1374,
 'retina': 1196,
 'nearsighted': 925,
 'nearsightedness': 926,
 'detachment': 357,
 'atla': 77,
 'posterior': 1122,
 'optic': 994,
 'tissue': 1496,
 'epiretinal': 452,
 'macular': 827,
 'cone': 286,
 'cornea': 303,
 'iris': 736,
 'chamber': 219,
 'corneas': 305,
 'vitamin': 1622,
 'intraocular': 723,
 'pigment': 1096,
 'granule': 610,
 'halos': 636,
 'blocking': 127,
 'farsighte': 498,
 'neuropathie': 948,
 'myelin': 912,
 'neuritis': 940,
 'field': 517,
 'walnut': 1634,
 'neovascular': 931,
 'eyebrow': 488,
 'melanin': 862,
 'nystagmus': 977,
 'farsightedness': 499,
 'astigmatism': 73,
 'ventricles': 1592,
 'edema': 421,
 'size': 1297,
 'enlargement': 440,
 'hormone': 661,
 'producing': 1143,
 'pituitary': 1103,
 'irregular': 738,
 'heartbeat': 646,
 'shin': 1277,
 'top': 1508,
 'goiter': 602,
 'diarrhea': 360,
 'adrenal': 16,
 'endocrine': 433,
 'child': 229,
 'bean': 105,
 'shaped': 1274,
 'tumor': 1537,
 'prolactinoma': 1145,
 'apoplexy': 53,
 'meibomian': 861,
 'productiondry': 1144,
 'lacrimal': 763,
 'blink': 123,
 'ectropion': 419,
 'entropion': 442,
 'eyeglass': 489,
 'decrease': 347,
 'scleral': 1243,
 'lense': 787,
 'distort': 377,
 'sclera': 1242,
 'lining': 807,
 'crust': 329,
 'sympathetic': 1431,
 'pupillary': 1165,
 'aorta': 50,
 'drooping': 390,
 'dim': 367,
 'ptosis': 1154,
 'par': 1046,
 'plana': 1105,
 'salmon': 1229,
 'choroid': 236,
 'ciliary': 243,
 'musclesmyasthenia': 909,
 'filtering': 520,
 'steak': 1353,
 'neuromuscular': 944,
 'jellylike': 748,
 'clarity': 253,
 'injurysymptom': 700,
 'altered': 27,
 'sense': 1262,
 'bedsore': 107,
 'cardiac': 188,
 'hodgkin': 660,
 'extremity': 485,
 'shooting': 1280,
 'spina': 1334,
 'bifida': 112,
 'gi': 591,
 'vertebrae': 1600,
 'bowman': 141,
 'rm': 1211,
 'sleepwalk': 1305,
 'terror': 1465,
 'deprivation': 352,
 'daytime': 343,
 'nightmare': 953,
 'maxillofacial': 850,
 'surgeon': 1416,
 'atrial': 79,
 'leave': 783,
 'ovary': 1018,
 'snore': 1316,
 'sweat': 1424,
 'temple': 1453,
 'dull': 400,
 'manic': 836,
 'mood': 894,
 'phrenic': 1092,
 'atrophy': 80,
 'bmc': 136,
 'sap': 1232,
 'vascular': 1579,
 'cortical': 311,
 'biting': 115,
 'intellectual': 708,
 'disability': 368,
 'venous': 1589,
 'synapsis': 1434,
 'sr': 1349,
 'muscular': 910,
 'pancreas': 1037,
 'orchitis': 1000,
 'pancreatitis': 1039,
 'testicle': 1466,
 'droplet': 393,
 'vestibulocochlear': 1613,
 'covering': 316,
 'pineal': 1099,
 'mass': 841,
 'chromosomal': 239,
 'hyperactivity': 667,
 'endovascular': 438,
 'aneurysm': 35,
 'aneurysmal': 36,
 'subarachnoid': 1384,
 'avm': 88,
 'neurovascular': 950,
 'poor': 1118,
 'grade': 605,
 'large': 771,
 'giant': 592,
 'rupture': 1219,
 'droop': 389,
 'reflexe': 1185,
 'cavernous': 197,
 'malformation': 831,
 'intracerebral': 719,
 'torcular': 1510,
 'dural': 402,
 'basal': 101,
 'ganglia': 577,
 'ccms': 201,
 'cerebrovascular': 210,
 'section': 1251,
 'ccm': 200,
 'nut': 976,
 'balloonlike': 96,
 'clump': 263,
 'seed': 1253,
 'difficultie': 361,
 'decline': 346,
 'think': 1476,
 'arteriovenous': 68,
 'fm': 539,
 'nonprimary': 965,
 'throb': 1479,
 'craniofacial': 320,
 'scalp': 1234,
 'breakfast': 147,
 'pallor': 1032,
 'barotrauma': 99,
 'worsen': 1648,
 'vomit': 1627,
 'hematoma': 650,
 'intravenously': 730,
 'cerebellar': 206,
 'pound': 1129,
 'inattentiveness': 683,
 'shrinkage': 1283,
 'malaise': 829,
 'knee': 757,
 'symptom': 1432,
 'marrow': 840,
 'eczema': 420,
 'cochlear': 267,
 'crusty': 330,
 'septum': 1268,
 'polyp': 1111,
 'whiplash': 1642,
 'type': 1544,
 'eyeglasse': 490,
 'tensing': 1461,
 'substantia': 1402,
 'nigra': 954,
 'smile': 1312,
 'glossopharyngeal': 600,
 'stool': 1364,
 'gerd': 590,
 'burning': 169,
 'erythema': 463,
 'migran': 880,
 'chew': 227,
 'fissured': 523,
 'milk': 882,
 'hypothalamus': 676,
 'sjögren': 1299,
 'coin': 268,
 'nodule': 961,
 'testis': 1468,
 'sack': 1223,
 'nodosum': 959,
 'vena': 1588,
 'cava': 196,
 'intestine': 715,
 'starchy': 1352,
 'flatten': 530,
 'shoulder': 1282,
 'map': 838,
 'dot': 384,
 'fingerprint': 521,
 'thin': 1475,
 'erosion': 460,
 'stroma': 1376,
 'epithelial': 455,
 'vernal': 1598,
 'keratoconjunctivitis': 754,
 'cloudy': 262,
 'scaly': 1235,
 'corner': 306,
 'greasy': 616,
 'hemisphere': 651,
 'lateral': 778,
 'geniculate': 586,
 'nucleus': 973,
 'bumping': 167,
 'technically': 1449,
 'pink': 1100,
 'blepharospasm': 120,
 'discolor': 371,
 'green': 617,
 'sternum': 1357,
 'rosacea': 1215,
 'droopy': 391,
 'cervical': 215,
 'ehlers': 424,
 'danlos': 341,
 'blunt': 133,
 'chalazia': 218,
 'sinus': 1294,
 'luncheon': 820,
 'meat': 851,
 'pepperoni': 1068,
 'susac': 1418,
 'psychosis': 1151,
 'disturbance': 378,
 'halo': 635,
 'axon': 91,
 'nosebleed': 968,
 'purplish': 1166,
 'crook': 328,
 'mitochondrial': 887,
 'meningoencephalocele': 870,
 'catheter': 192,
 'epidural': 449,
 'base': 102,
 'hashimoto': 639,
 'multi': 906,
 'nodular': 960,
 'material': 846,
 'thicken': 1473,
 'contract': 298,
 'energy': 439,
 'steroid': 1358,
 'amyloid': 31,
 'eclampsia': 416,
 'postpartum': 1126,
 'neonatal': 929,
 'intraventricular': 731,
 'shallowly': 1273,
 'tint': 1494,
 'gunshot': 627,
 'horner': 662,
 'hemorrhage': 652,
 'visuospatial': 1621,
 'misshaped': 885,
 'with': 1645,
 'foraman': 546,
 'magnum': 828,
 'cheekbone': 223,
 'passageway': 1060,
 'temporomandibular': 1456,
 'crack': 317,
 'spinocerebellar': 1337,
 'pharyngeal': 1086,
 'flap': 527,
 'vpi': 1629,
 'ribcage': 1207,
 'peroxisome': 1083,
 'hippocampal': 658,
 'gut': 629,
 'focal': 540,
 'fungal': 573,
 'shrivel': 1284,
 'forelock': 551,
 'feel': 510,
 'food': 544,
 'stuck': 1378,
 'sputumjaw': 1347,
 'error': 461,
 'refraction': 1187,
 'cheilitis': 225,
 'simplex': 1291,
 'chap': 221,
 'peel': 1064,
 'trachea': 1513,
 'raspy': 1176,
 'ulcers': 1549,
 'regurgitation': 1190,
 'anesthesia': 34,
 'myofascial': 914,
 'foraminal': 548,
 'radiate': 1173,
 'multiorgan': 907,
 'whitish': 1644,
 'coat': 265,
 'villosa': 1616,
 'swellingloss': 1429,
 'prolonged': 1146,
 'mandible': 834,
 'maxilla': 848,
 'sebaceous': 1247,
 'sty': 1379,
 'cheeks': 224,
 'paranasal': 1049,
 'drainage': 385,
 'drooling': 388,
 'obstruction': 981,
 'matting': 847,
 'endolymphatic': 435,
 'hydrop': 666,
 'trembling': 1519,
 'sound': 1324,
 'alter': 26,
 'teary': 1447,
 'epiphora': 451,
 'interstitial': 713,
 'color': 277,
 'conjunctivae': 290,
 'molluscum': 890,
 'contagiosum': 296,
 'eyelashe': 492,
 'grimace': 619,
 'lens': 786,
 'colored': 278,
 'painheadacheeye': 1024,
 'squint': 1348,
 'oromandibular': 1004,
 'papilledema': 1041,
 'asteroid': 72,
 'floppy': 535,
 'sphincter': 1331,
 'mid': 875,
 'hiatal': 655,
 'arachnoid': 56,
 'pulmonic': 1158,
 'granuloma': 611,
 'suppurative': 1412,
 'papular': 1043,
 'cutaneous': 337,
 'punctum': 1162,
 'branchial': 146,
 'punctate': 1161,
 'cricopharyngeus': 325,
 'submucosal': 1397,
 'layer': 779,
 'zenker': 1652,
 'mucosa': 901,
 'oblique': 979,
 'retropharyngeal': 1203,
 'intravenous': 729,
 'innervate': 702,
 'vagus': 1575,
 'auriculotemporal': 85,
 'vii': 1614,
 'plexu': 1109,
 'neural': 938,
 'network': 937,
 'pathology': 1063,
 'laryngeal': 772,
 'nasopharyngeal': 922,
 'ethmoid': 470,
 'faucial': 504,
 'maxillary': 849,
 'pyogenicum': 1170,
 'intraoral': 724,
 'epuli': 458,
 'gravidarum': 613,
 'papule': 1044,
 'renal': 1192,
 'friable': 565,
 'anteriorly': 44,
 'part': 1058,
 'orbicularis': 997,
 'oculi': 987,
 'inferior': 691,
 'canaliculus': 182,
 'superior': 1407,
 'crest': 324,
 'turbinate': 1538,
 'medially': 855,
 'nasolacrimal': 921,
 'fossa': 557,
 'dcr': 345,
 'medial': 854,
 'nldo': 956,
 'fundus': 572,
 'mucosal': 902,
 'ostium': 1011,
 'ethmoidal': 471,
 'excretory': 474,
 'air': 22,
 'naris': 918,
 'slit': 1307,
 'axilla': 90,
 'mucocele': 899,
 'uncinate': 1553,
 'bulla': 164,
 'soft': 1318,
 'infundibulum': 697,
 'incision': 684,
 'canalicular': 181,
 'periorbita': 1074,
 'conjunctival': 291,
 'fornix': 555,
 ...}

In [110]:
# Converting our first sample into a vector
v0 = vectorizer.transform(df.data).toarray()

In [151]:
X_train, X_test, y_train, y_test = train_test_split(df['anat_symp_lem'], df['label'], test_size = 0.3, random_state=42)

In [152]:
vectorizer = CountVectorizer()
tfidfzer = TfidfTransformer()
lr = LogisticRegression()

In [153]:
vectors = vectorizer.fit_transform(X_train)
tfidf = tfidfzer.fit_transform(vectors)

In [154]:
# clf = LogisticRegression().fit(X_train_tfidf, y_train)

In [155]:
lr.fit(tfidf,y_train)

LogisticRegression()

In [156]:
vectors_test = vectorizer.transform(X_test)

In [157]:
pred = lr.predict(vectors_test)

In [164]:
from sklearn import metrics

acc_score = metrics.accuracy_score(y_test, pred)
f1_score = metrics.f1_score(y_test, pred, average='macro')

print('Total accuracy classification score: {}'.format(acc_score))
print('Total F1 classification score: {}'.format(f1_score))

Total accuracy classification score: 0.8741496598639455
Total F1 classification score: 0.875514754396742

In [165]:
from sklearn.metrics import classification_report
classification_report(y_test, pred)

'                   precision    recall  f1-score   support\n\nEar, Nose, Throat       0.90      0.83      0.87       102\n      Neurologist       0.82      0.87      0.85       101\n  Ophthalmologist       0.90      0.92      0.91        91\n\n         accuracy                           0.87       294\n        macro avg       0.88      0.88      0.88       294\n     weighted avg       0.88      0.87      0.87       294\n'

In [168]:

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, pred)

array([[85, 15,  2],
       [ 6, 88,  7],
       [ 3,  4, 84]], dtype=int64)

In [174]:
text = ["my head hurts and eyes are watering. ache in temple area."]
doc = ''.join(list(lr.predict(vectorizer.transform(text))))
doc

'Neurologist'

In [178]:
import pickle

In [179]:
Pkl_Filename = "CheckApp_LR_Model.picle"

In [180]:
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(lr, file)